/**
 * IBM Blockchain Platform Service API
 * The Blockchain Service API allows you to interact with your blockchain network.  The APIs listed in this doc are authenticated using basic auth, where the username and password correspond to a user org and secret that are included in your service credentials.  See the ConnectionProfile schema under the Models for more information.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.BlockInformationParsed;


/**
 * Describes the contents of a block in a channel
 */
@ApiModel(description = "Describes the contents of a block in a channel")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2018-03-28T22:08:33.832-05:00")
public class BlockInformation   {
  @SerializedName("parsed")
  private BlockInformationParsed parsed = null;

  @SerializedName("peer_url")
  private String peerUrl = null;

  @SerializedName("channel_id")
  private String channelId = null;

  public BlockInformation parsed(BlockInformationParsed parsed) {
    this.parsed = parsed;
    return this;
  }

   /**
   * Get parsed
   * @return parsed
  **/
  @ApiModelProperty(example = "null", value = "")
  public BlockInformationParsed getParsed() {
    return parsed;
  }

  public void setParsed(BlockInformationParsed parsed) {
    this.parsed = parsed;
  }

  public BlockInformation peerUrl(String peerUrl) {
    this.peerUrl = peerUrl;
    return this;
  }

   /**
   * The GRPC url that was used to retrieve the block information.  It should point to a peer on the network.
   * @return peerUrl
  **/
  @ApiModelProperty(example = "null", value = "The GRPC url that was used to retrieve the block information.  It should point to a peer on the network.")
  public String getPeerUrl() {
    return peerUrl;
  }

  public void setPeerUrl(String peerUrl) {
    this.peerUrl = peerUrl;
  }

  public BlockInformation channelId(String channelId) {
    this.channelId = channelId;
    return this;
  }

   /**
   * The name of the channel that the block belongs to
   * @return channelId
  **/
  @ApiModelProperty(example = "null", value = "The name of the channel that the block belongs to")
  public String getChannelId() {
    return channelId;
  }

  public void setChannelId(String channelId) {
    this.channelId = channelId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BlockInformation blockInformation = (BlockInformation) o;
    return Objects.equals(this.parsed, blockInformation.parsed) &&
        Objects.equals(this.peerUrl, blockInformation.peerUrl) &&
        Objects.equals(this.channelId, blockInformation.channelId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(parsed, peerUrl, channelId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BlockInformation {\n");
    
    sb.append("    parsed: ").append(toIndentedString(parsed)).append("\n");
    sb.append("    peerUrl: ").append(toIndentedString(peerUrl)).append("\n");
    sb.append("    channelId: ").append(toIndentedString(channelId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

