/**
 * IBM Blockchain Platform Service API
 * The Blockchain Service API allows you to interact with your blockchain network.  The APIs listed in this doc are authenticated using basic auth, where the username and password correspond to a user org and secret that are included in your service credentials.  See the ConnectionProfile schema under the Models for more information.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ChannelStatsHeight;


/**
 * Describes various metrics of a channel
 */
@ApiModel(description = "Describes various metrics of a channel")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2018-03-28T22:08:33.832-05:00")
public class ChannelStats   {
  @SerializedName("height")
  private ChannelStatsHeight height = null;

  @SerializedName("currentBlockHash")
  private String currentBlockHash = null;

  @SerializedName("previousBlockHash")
  private String previousBlockHash = null;

  @SerializedName("peer_url")
  private String peerUrl = null;

  @SerializedName("sequence")
  private Object sequence = null;

  @SerializedName("channel_id")
  private String channelId = null;

  public ChannelStats height(ChannelStatsHeight height) {
    this.height = height;
    return this;
  }

   /**
   * Get height
   * @return height
  **/
  @ApiModelProperty(example = "null", value = "")
  public ChannelStatsHeight getHeight() {
    return height;
  }

  public void setHeight(ChannelStatsHeight height) {
    this.height = height;
  }

  public ChannelStats currentBlockHash(String currentBlockHash) {
    this.currentBlockHash = currentBlockHash;
    return this;
  }

   /**
   * The hash of the latest block on the channel
   * @return currentBlockHash
  **/
  @ApiModelProperty(example = "null", value = "The hash of the latest block on the channel")
  public String getCurrentBlockHash() {
    return currentBlockHash;
  }

  public void setCurrentBlockHash(String currentBlockHash) {
    this.currentBlockHash = currentBlockHash;
  }

  public ChannelStats previousBlockHash(String previousBlockHash) {
    this.previousBlockHash = previousBlockHash;
    return this;
  }

   /**
   * The hash of the block before the latest block on the channel
   * @return previousBlockHash
  **/
  @ApiModelProperty(example = "null", value = "The hash of the block before the latest block on the channel")
  public String getPreviousBlockHash() {
    return previousBlockHash;
  }

  public void setPreviousBlockHash(String previousBlockHash) {
    this.previousBlockHash = previousBlockHash;
  }

  public ChannelStats peerUrl(String peerUrl) {
    this.peerUrl = peerUrl;
    return this;
  }

   /**
   * The GRPC url of the peer that provided the channel information
   * @return peerUrl
  **/
  @ApiModelProperty(example = "null", value = "The GRPC url of the peer that provided the channel information")
  public String getPeerUrl() {
    return peerUrl;
  }

  public void setPeerUrl(String peerUrl) {
    this.peerUrl = peerUrl;
  }

  public ChannelStats sequence(Object sequence) {
    this.sequence = sequence;
    return this;
  }

   /**
   * Get sequence
   * @return sequence
  **/
  @ApiModelProperty(example = "null", value = "")
  public Object getSequence() {
    return sequence;
  }

  public void setSequence(Object sequence) {
    this.sequence = sequence;
  }

  public ChannelStats channelId(String channelId) {
    this.channelId = channelId;
    return this;
  }

   /**
   * The name of the channel
   * @return channelId
  **/
  @ApiModelProperty(example = "null", value = "The name of the channel")
  public String getChannelId() {
    return channelId;
  }

  public void setChannelId(String channelId) {
    this.channelId = channelId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChannelStats channelStats = (ChannelStats) o;
    return Objects.equals(this.height, channelStats.height) &&
        Objects.equals(this.currentBlockHash, channelStats.currentBlockHash) &&
        Objects.equals(this.previousBlockHash, channelStats.previousBlockHash) &&
        Objects.equals(this.peerUrl, channelStats.peerUrl) &&
        Objects.equals(this.sequence, channelStats.sequence) &&
        Objects.equals(this.channelId, channelStats.channelId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(height, currentBlockHash, previousBlockHash, peerUrl, sequence, channelId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChannelStats {\n");
    
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("    currentBlockHash: ").append(toIndentedString(currentBlockHash)).append("\n");
    sb.append("    previousBlockHash: ").append(toIndentedString(previousBlockHash)).append("\n");
    sb.append("    peerUrl: ").append(toIndentedString(peerUrl)).append("\n");
    sb.append("    sequence: ").append(toIndentedString(sequence)).append("\n");
    sb.append("    channelId: ").append(toIndentedString(channelId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

