/**
 * IBM Blockchain Platform Service API
 * The Blockchain Service API allows you to interact with your blockchain network.  The APIs listed in this doc are authenticated using basic auth, where the username and password correspond to a user org and secret that are included in your service credentials.  See the ConnectionProfile schema under the Models for more information.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;


/**
 * ChannelStatsHeight
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2018-03-28T22:08:33.832-05:00")
public class ChannelStatsHeight   {
  @SerializedName("low")
  private BigDecimal low = null;

  @SerializedName("high")
  private BigDecimal high = null;

  @SerializedName("unsigned")
  private Boolean unsigned = null;

  public ChannelStatsHeight low(BigDecimal low) {
    this.low = low;
    return this;
  }

   /**
   * The number of blocks on the channel
   * @return low
  **/
  @ApiModelProperty(example = "null", value = "The number of blocks on the channel")
  public BigDecimal getLow() {
    return low;
  }

  public void setLow(BigDecimal low) {
    this.low = low;
  }

  public ChannelStatsHeight high(BigDecimal high) {
    this.high = high;
    return this;
  }

   /**
   * Get high
   * @return high
  **/
  @ApiModelProperty(example = "null", value = "")
  public BigDecimal getHigh() {
    return high;
  }

  public void setHigh(BigDecimal high) {
    this.high = high;
  }

  public ChannelStatsHeight unsigned(Boolean unsigned) {
    this.unsigned = unsigned;
    return this;
  }

   /**
   * Get unsigned
   * @return unsigned
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getUnsigned() {
    return unsigned;
  }

  public void setUnsigned(Boolean unsigned) {
    this.unsigned = unsigned;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChannelStatsHeight channelStatsHeight = (ChannelStatsHeight) o;
    return Objects.equals(this.low, channelStatsHeight.low) &&
        Objects.equals(this.high, channelStatsHeight.high) &&
        Objects.equals(this.unsigned, channelStatsHeight.unsigned);
  }

  @Override
  public int hashCode() {
    return Objects.hash(low, high, unsigned);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChannelStatsHeight {\n");
    
    sb.append("    low: ").append(toIndentedString(low)).append("\n");
    sb.append("    high: ").append(toIndentedString(high)).append("\n");
    sb.append("    unsigned: ").append(toIndentedString(unsigned)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

