/**
 * IBM Blockchain Platform Service API
 * The Blockchain Service API allows you to interact with your blockchain network.  The APIs listed in this doc are authenticated using basic auth, where the username and password correspond to a user org and secret that are included in your service credentials.  See the ConnectionProfile schema under the Models for more information.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ConnectionProfileCertificateAuthoritiesFabriccaorgIDcaIDRegistrar;
import io.swagger.client.model.ConnectionProfileCertificateAuthoritiesFabriccaorgIDcaIDTlsCACerts;
import java.util.ArrayList;
import java.util.List;


/**
 * Information needed to establish a connection to a single CA
 */
@ApiModel(description = "Information needed to establish a connection to a single CA")
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2018-03-28T22:08:33.832-05:00")
public class ConnectionProfileCertificateAuthoritiesFabriccaorgIDcaID   {
  @SerializedName("url")
  private String url = null;

  @SerializedName("httpOptions")
  private Object httpOptions = null;

  @SerializedName("tlsCACerts")
  private ConnectionProfileCertificateAuthoritiesFabriccaorgIDcaIDTlsCACerts tlsCACerts = null;

  @SerializedName("registrar")
  private List<ConnectionProfileCertificateAuthoritiesFabriccaorgIDcaIDRegistrar> registrar = new ArrayList<ConnectionProfileCertificateAuthoritiesFabriccaorgIDcaIDRegistrar>();

  @SerializedName("caName")
  private String caName = null;

  @SerializedName("x-mspid")
  private String xMspid = null;

  public ConnectionProfileCertificateAuthoritiesFabriccaorgIDcaID url(String url) {
    this.url = url;
    return this;
  }

   /**
   * The endpoint for connecting to the fabric CA
   * @return url
  **/
  @ApiModelProperty(example = "null", value = "The endpoint for connecting to the fabric CA")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public ConnectionProfileCertificateAuthoritiesFabriccaorgIDcaID httpOptions(Object httpOptions) {
    this.httpOptions = httpOptions;
    return this;
  }

   /**
   * HTTP connection options that should be used when sending requests to the CA
   * @return httpOptions
  **/
  @ApiModelProperty(example = "null", value = "HTTP connection options that should be used when sending requests to the CA")
  public Object getHttpOptions() {
    return httpOptions;
  }

  public void setHttpOptions(Object httpOptions) {
    this.httpOptions = httpOptions;
  }

  public ConnectionProfileCertificateAuthoritiesFabriccaorgIDcaID tlsCACerts(ConnectionProfileCertificateAuthoritiesFabriccaorgIDcaIDTlsCACerts tlsCACerts) {
    this.tlsCACerts = tlsCACerts;
    return this;
  }

   /**
   * Get tlsCACerts
   * @return tlsCACerts
  **/
  @ApiModelProperty(example = "null", value = "")
  public ConnectionProfileCertificateAuthoritiesFabriccaorgIDcaIDTlsCACerts getTlsCACerts() {
    return tlsCACerts;
  }

  public void setTlsCACerts(ConnectionProfileCertificateAuthoritiesFabriccaorgIDcaIDTlsCACerts tlsCACerts) {
    this.tlsCACerts = tlsCACerts;
  }

  public ConnectionProfileCertificateAuthoritiesFabriccaorgIDcaID registrar(List<ConnectionProfileCertificateAuthoritiesFabriccaorgIDcaIDRegistrar> registrar) {
    this.registrar = registrar;
    return this;
  }

  public ConnectionProfileCertificateAuthoritiesFabriccaorgIDcaID addRegistrarItem(ConnectionProfileCertificateAuthoritiesFabriccaorgIDcaIDRegistrar registrarItem) {
    this.registrar.add(registrarItem);
    return this;
  }

   /**
   * A list of enrollment IDs and secrets for the CA
   * @return registrar
  **/
  @ApiModelProperty(example = "null", value = "A list of enrollment IDs and secrets for the CA")
  public List<ConnectionProfileCertificateAuthoritiesFabriccaorgIDcaIDRegistrar> getRegistrar() {
    return registrar;
  }

  public void setRegistrar(List<ConnectionProfileCertificateAuthoritiesFabriccaorgIDcaIDRegistrar> registrar) {
    this.registrar = registrar;
  }

  public ConnectionProfileCertificateAuthoritiesFabriccaorgIDcaID caName(String caName) {
    this.caName = caName;
    return this;
  }

   /**
   * The friendly name for the CA
   * @return caName
  **/
  @ApiModelProperty(example = "null", value = "The friendly name for the CA")
  public String getCaName() {
    return caName;
  }

  public void setCaName(String caName) {
    this.caName = caName;
  }

  public ConnectionProfileCertificateAuthoritiesFabriccaorgIDcaID xMspid(String xMspid) {
    this.xMspid = xMspid;
    return this;
  }

   /**
   * The MSP ID represented by this CA
   * @return xMspid
  **/
  @ApiModelProperty(example = "null", value = "The MSP ID represented by this CA")
  public String getXMspid() {
    return xMspid;
  }

  public void setXMspid(String xMspid) {
    this.xMspid = xMspid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConnectionProfileCertificateAuthoritiesFabriccaorgIDcaID connectionProfileCertificateAuthoritiesFabriccaorgIDcaID = (ConnectionProfileCertificateAuthoritiesFabriccaorgIDcaID) o;
    return Objects.equals(this.url, connectionProfileCertificateAuthoritiesFabriccaorgIDcaID.url) &&
        Objects.equals(this.httpOptions, connectionProfileCertificateAuthoritiesFabriccaorgIDcaID.httpOptions) &&
        Objects.equals(this.tlsCACerts, connectionProfileCertificateAuthoritiesFabriccaorgIDcaID.tlsCACerts) &&
        Objects.equals(this.registrar, connectionProfileCertificateAuthoritiesFabriccaorgIDcaID.registrar) &&
        Objects.equals(this.caName, connectionProfileCertificateAuthoritiesFabriccaorgIDcaID.caName) &&
        Objects.equals(this.xMspid, connectionProfileCertificateAuthoritiesFabriccaorgIDcaID.xMspid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(url, httpOptions, tlsCACerts, registrar, caName, xMspid);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConnectionProfileCertificateAuthoritiesFabriccaorgIDcaID {\n");
    
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    httpOptions: ").append(toIndentedString(httpOptions)).append("\n");
    sb.append("    tlsCACerts: ").append(toIndentedString(tlsCACerts)).append("\n");
    sb.append("    registrar: ").append(toIndentedString(registrar)).append("\n");
    sb.append("    caName: ").append(toIndentedString(caName)).append("\n");
    sb.append("    xMspid: ").append(toIndentedString(xMspid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

