/**
 * IBM Blockchain Platform Service API
 * The Blockchain Service API allows you to interact with your blockchain network.  The APIs listed in this doc are authenticated using basic auth, where the username and password correspond to a user org and secret that are included in your service credentials.  See the ConnectionProfile schema under the Models for more information.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.api;

import ibp_java_client.ApiException;
import io.swagger.client.model.InlineResponse4001;
import io.swagger.client.model.PeerList;
import io.swagger.client.model.BlockInformation;
import io.swagger.client.model.ChannelStats;
import io.swagger.client.model.InlineResponse400;
import io.swagger.client.model.CertificateList;
import io.swagger.client.model.InlineResponse2001;
import io.swagger.client.model.InlineResponse200;
import io.swagger.client.model.StandardBody;
import io.swagger.client.model.InlineResponse500;
import io.swagger.client.model.InlineResponse2002;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ChannelsApi
 */
public class ChannelsApiTest {

    private final ChannelsApi api = new ChannelsApi();

    
    /**
     * See a block
     *
     * Get the contents of given block
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getChannelBlockTest() throws ApiException {
        String networkID = null;
        String channelID = null;
        String blockNo = null;
        PeerList body = null;
        // BlockInformation response = api.getChannelBlock(networkID, channelID, blockNo, body);

        // TODO: test validations
    }
    
    /**
     * See basic channel stats
     *
     * Get a report on various channel metrics
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getChannelMetricsTest() throws ApiException {
        String networkID = null;
        String channelID = null;
        // ChannelStats response = api.getChannelMetrics(networkID, channelID);

        // TODO: test validations
    }
    
    /**
     * List channels on peers
     *
     * Retreives a list of channels from each of the peers given in the body of the request
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getChannelsFromPeersTest() throws ApiException {
        String networkID = null;
        PeerList body = null;
        // CertificateList response = api.getChannelsFromPeers(networkID, body);

        // TODO: test validations
    }
    
    /**
     * See the channel members
     *
     * Get a list of the members for a given channel
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listChannelMembersTest() throws ApiException {
        String networkID = null;
        String channelID = null;
        // List<InlineResponse2001> response = api.listChannelMembers(networkID, channelID);

        // TODO: test validations
    }
    
    /**
     * See instantiated chaincodes
     *
     * Get a list of the instantiated chaincodes for a given channel
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listInstantiatedChaincodesTest() throws ApiException {
        String networkID = null;
        String channelID = null;
        StandardBody body = null;
        // InlineResponse200 response = api.listInstantiatedChaincodes(networkID, channelID, body);

        // TODO: test validations
    }
    
    /**
     * Sync channel certificates
     *
     * Synchronizes the list of certificates for a given channel across a list of peers.  Useful for making sure all your peers can verify signatures for a given channel.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void syncChannelCertsTest() throws ApiException {
        String networkID = null;
        String channelID = null;
        // InlineResponse2002 response = api.syncChannelCerts(networkID, channelID);

        // TODO: test validations
    }
    
}
