/**
 * IBM Blockchain Platform Service API
 * The Blockchain Service API allows you to interact with your blockchain network.  The APIs listed in this doc are authenticated using basic auth, where the username and password correspond to a user org and secret that are included in your service credentials.  See the ConnectionProfile schema under the Models for more information.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.api;

import ibp_java_client.ApiException;
import io.swagger.client.model.PeerList;
import io.swagger.client.model.ChannelList;
import io.swagger.client.model.NodeStatuses;
import io.swagger.client.model.ConnectionProfile;
import io.swagger.client.model.CertUpload;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for NetworksApi
 */
public class NetworksApiTest {

    private final NetworksApi api = new NetworksApi();

    
    /**
     * List certificates
     *
     * Acquires a list of certificates from each of the peers given in the body of the request
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCertificatesFromPeersTest() throws ApiException {
        String networkID = null;
        PeerList body = null;
        // ChannelList response = api.getCertificatesFromPeers(networkID, body);

        // TODO: test validations
    }
    
    /**
     * Get the status of your blockchain nodes
     *
     * Returns the operational status of all your nodes on the network
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getNetworkNodesStatusTest() throws ApiException {
        String networkID = null;
        // NodeStatuses response = api.getNetworkNodesStatus(networkID);

        // TODO: test validations
    }
    
    /**
     * Get the connection profile
     *
     * Gets the connection profile for a network, which has everything the HyperLedger fabric SDK needs to interact with the network.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getNetworkServiceCredsTest() throws ApiException {
        String networkID = null;
        // ConnectionProfile response = api.getNetworkServiceCreds(networkID);

        // TODO: test validations
    }
    
    /**
     * Add an admin certificate
     *
     * Upload an admin certificate to a given peer
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void uploadCertificateTest() throws ApiException {
        String networkID = null;
        CertUpload body = null;
        // api.uploadCertificate(networkID, body);

        // TODO: test validations
    }
    
}
