/**
 * IBM Blockchain Platform Service API
 * The Blockchain Service API allows you to interact with your blockchain network.  The APIs listed in this doc are authenticated using basic auth, where the username and password correspond to a user org and secret that are included in your service credentials.  See the ConnectionProfile schema under the Models for more information.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.api;

import ibp_java_client.ApiException;
import io.swagger.client.model.InlineResponse2002;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PeersApi
 */
public class PeersApiTest {

    private final PeersApi api = new PeersApi();

    
    /**
     * Start a peer
     *
     * Start a given peer
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void startPeerTest() throws ApiException {
        String networkID = null;
        String peerID = null;
        // InlineResponse2002 response = api.startPeer(networkID, peerID);

        // TODO: test validations
    }
    
    /**
     * Stop a peer
     *
     * Stop a given peer
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void stopPeerTest() throws ApiException {
        String networkID = null;
        String peerID = null;
        // InlineResponse2002 response = api.stopPeer(networkID, peerID);

        // TODO: test validations
    }
    
}
